### ISSUE TITLE
Lab is evil, gives a load of data to type with nowhere to copy paste from.

### ISSUE THREAD

**Issue by CodeF53** [learn-co-curriculum/phase-0-html-tables-lab#13]
### Canvas Link

https://learning.flatironschool.com/courses/5797/assignments/186171?module_item_id=413754

### Concern

I am breezing through this html lab stuff because I already know basically all of it, but this lab is a slog to get through.

Why on earth would you have us type out precise numbers from an image.

This lab made me unreasonably mad.

**Comment by lizbur10** [comment]
Hi @CodeF53! So sorry this lab annoyed you so much - I definitely feel your pain! 😄 Unfortunately, I don't really see a good way to fix it. It's there as a picture rather than in table format because we don't want students to be tempted to just copy/paste from the source html rather than constructing the table themselves. The other option is to provide a link to the source (https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population), but those figures are updated regularly so it would only be helpful until the figures didn't match the tests anymore. We will come up with a different example - one that uses smaller numbers - the next time we update this lesson, but for now I'm going to close this issue.

Thanks for contributing to the Flatiron School curriculum 💙
